name: layout_builder
description: Layout building templates for apps built by https://github.com/julienlebren 
version: 2.5.22
homepage: https://twitter.com/hikeland
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  extensions:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/extensions
    version: ^0.2.4
  localization:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/localization
    version: ^1.1.3
  modal_bottom_sheet:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/modal_bottom_sheet
    version: ^2.0.2-dev.1
  cached_network_image: ^3.1.0-alpha.1 
  flutter_riverpod: ^1.0.0
  intl: ^0.17.0
  freezed_annotation: ^1.1.0
  numberpicker: ^2.0.1
  page_transition: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  freezed: ^1.1.1

flutter:
  generate: true