name: layout_builder
description: Layout building templates for apps built by https://github.com/julienlebren 
version: 3.2.2
homepage: https://twitter.com/hikeland
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  extensions:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/extensions
    version: ^0.6.2
  localization:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/localization
    version: ^1.3.0
  modal_bottom_sheet:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/modal_bottom_sheet
    version: ^2.0.2
  cached_network_image: ^3.2.2
  flutter_riverpod: ^2.0.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  freezed_annotation: ^2.1.0
  numberpicker: ^2.0.1
  page_transition: ^2.0.5
  riverpod_annotation: ^1.0.2
  visibility_detector: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  flutter_lints: ^1.0.0
  freezed: ^2.1.0+1
  riverpod_generator: ^1.0.2

flutter:
  generate: true