name: layout_builder
description: Layout building templates for apps built by https://github.com/julienlebren 
version: 3.11.1
homepage: https://twitter.com/hikeland
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  extensions:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/extensions
    version: ^0.11.1
  localization:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/localization
    version: ^1.6.1
  modal_bottom_sheet: ^3.0.0-pre
  cached_network_image: ^3.3.1
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  freezed_annotation: ^2.4.3
  numberpicker: ^2.1.2
  page_transition: ^2.1.0
  riverpod_annotation: ^2.3.5
  visibility_detector: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.6
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0

flutter:
  generate: true