name: layout_builder
description: Layout building templates for apps built by https://github.com/julienlebren 
version: 3.6.0-dev.9.9.9.9.9.9.8
homepage: https://twitter.com/hikeland
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  extensions:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/extensions
    version: ^0.7.0
  localization:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/localization
    version: ^1.4.0
  modal_bottom_sheet: ^3.0.0-pre
  cached_network_image: ^3.2.2
  flutter_riverpod: ^2.1.1
  google_fonts: ^4.0.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  freezed_annotation: ^2.2.0
  numberpicker: ^2.0.1
  page_transition: ^2.0.5
  riverpod_annotation: ^1.0.6
  visibility_detector: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1 
  build_runner: ^2.3.2
  freezed: ^2.2.1
  riverpod_generator: ^1.0.6

flutter:
  generate: true