name: layout_builder
description: Layout building templates for apps built by https://github.com/julienlebren 
version: 3.9.0
homepage: https://twitter.com/hikeland
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  extensions:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/extensions
    version: ^0.8.0
  localization:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/localization
    version: ^1.4.0
  modal_bottom_sheet: ^3.0.0-pre
  cached_network_image: ^3.2.2
  flutter_riverpod: ^2.4.2
  google_fonts: ^4.0.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  freezed_annotation: ^2.4.1
  numberpicker: ^2.1.2
  page_transition: ^2.0.5
  riverpod_annotation: ^2.1.6
  visibility_detector: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1 
  build_runner: ^2.4.6
  freezed: ^2.4.3
  riverpod_generator: ^2.3.2

flutter:
  generate: true