name: layout_builder
description: Layout building templates for apps built by https://github.com/julienlebren 
version: 2.1.13+3
homepage: https://twitter.com/hikeland
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  extensions:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/extensions
    version: ^0.1.1
  localization:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/localization
    version: ^0.1.4
  cached_network_image: ^3.1.0-alpha.1 
  flutter_riverpod: ^1.0.0
  intl: ^0.17.0
  freezed_annotation: ^1.1.0
  modal_bottom_sheet: ^2.0.0
  numberpicker: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  freezed: ^1.1.1

flutter:
  generate: true