name: localization
description: A new Flutter package project.
publish_to: 'none' 
version: 1.3.1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  riverpod_annotation: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  flutter_lints: ^1.0.0
  riverpod_generator: ^1.0.2

flutter: