name: purchases
description: A new Flutter package project.
version: 1.2.0
homepage: https://twitter.com/hikeland
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  purchases_flutter: ^3.10.0
  freezed_annotation: ^1.1.0
  flutter_riverpod: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  freezed: ^1.1.1
  flutter_lints: ^1.0.0

flutter: