name: purchases
description: A new Flutter package project.
version: 2.2.1-dev.0
homepage: https://twitter.com/hikeland
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  extensions:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/extensions
    version: ^0.2.0
  layout_builder:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/layout_builder
    version: ^2.4.3
  localization:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/localization
    version: ^1.1.3
  purchases_flutter: ^3.10.0
  freezed_annotation: ^1.1.0
  flutter_riverpod: ^1.0.0
  intl: ^0.17.0
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  freezed: ^1.1.1
  flutter_lints: ^1.0.0

flutter: