name: purchases
description: A package to handle purchases with RevenueCat and provide some layout stuff to build purchase pages.
version: 2.10.0
homepage: https://twitter.com/hikeland
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  extensions:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/extensions
    version: ^0.6.2
  layout_builder:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/layout_builder
    version: ^3.2.0
  localization:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/localization
    version: ^1.3.0
  purchases_flutter: ^4.4.1
  freezed_annotation: ^2.2.0
  flutter_riverpod: ^2.1.1
  intl: ^0.17.0
  riverpod_annotation: ^1.0.6
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1 
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  riverpod_generator: ^1.0.6

flutter: