name: purchases
description: A package to handle purchases with RevenueCat and provide some layout stuff to build purchase pages.
version: 2.12.0
homepage: https://twitter.com/hikeland
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  extensions:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/extensions
    version: ^0.8.0
  layout_builder:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/layout_builder
    version: ^3.8.0
  localization:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/localization
    version: ^1.4.0
  purchases_flutter: ^4.4.1
  freezed_annotation: ^2.2.0
  flutter_riverpod: ^2.1.1
  intl: ^0.18.1
  riverpod_annotation: ^1.0.6
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1 
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  riverpod_generator: ^1.0.6

flutter: