name: purchases
description: A new Flutter package project.
version: 2.9.0-dev.9.9.3
homepage: https://twitter.com/hikeland
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  extensions:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/extensions
    version: ^0.6.0
  layout_builder:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/layout_builder
    version: ^3.2.0
  localization:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/localization
    version: ^1.3.0
  purchases_flutter: ^4.2.1
  freezed_annotation: ^2.1.0
  flutter_riverpod: ^2.0.2
  intl: ^0.17.0
  riverpod_annotation: ^1.0.2
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  flutter_lints: ^1.0.0
  freezed: ^2.1.0+1
  riverpod_generator: ^1.0.2

flutter: