name: notifications
description: Notifications service for apps built by https://github.com/julienlebren 
version: 0.7.0
homepage: https://twitter.com/hikeland
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^15.0.3
  flutter_app_badger: ^1.5.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.2

dependency_overrides:
  meta: ">=1.11.0 <1.15.0"

flutter: