name: notifications
description: Notifications service for apps built by https://github.com/julienlebren 
version: 0.4.2
homepage: https://twitter.com/hikeland
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  firebase_messaging: ^13.0.1
  riverpod_annotation: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  riverpod_generator: ^1.0.2
  
flutter: