name: sign_in
description: Sign-in Flow Management for Flutter & Firebase
publish_to: 'none'
version: 6.6.1+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  extensions:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/extensions
    version: ^0.6.0
  firestore_service:
    git: 
      url: https://github.com/julienlebren/flutter_packages
      path: packages/firestore_service
    version: ^0.5.0
  firebase_storage_service:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/firebase_storage_service 
    version: ^0.6.0 
  layout_builder:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/layout_builder
    version: ^3.2.0
  localization:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/localization
    version: ^1.3.1
  cloud_functions: ^4.0.2
  firebase_auth: ^4.0.2
  freezed_annotation: ^2.1.0
  flutter_libphonenumber: 1.1.0
  flutter_login_facebook: ^1.6.0
  flutter_riverpod: ^2.0.2
  google_sign_in: ^5.4.2
  intl: ^0.17.0
  pinput: ^2.2.12
  riverpod_annotation: ^1.0.2
  the_apple_sign_in: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  flutter_lints: ^1.0.0
  freezed: ^2.1.1
  json_serializable: ^6.3.1
  riverpod_generator: ^1.0.2

flutter:
  generate: true
  assets:
    - assets/images/