name: sign_in
description: Sign In Flow Management for Flutter & Firebase
publish_to: 'none' 
version: 0.1.0+5

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth_service:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/firebase_auth_service
    version: ^0.4.0
  layout_builder:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/layout_builder
    version: ^0.17.0
  freezed_annotation: ^0.15.0
  flutter_riverpod: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  freezed: ^0.15.0
  flutter_lints: ^1.0.0
  sign_in_with_apple: ^3.3.0
  
flutter: