name: ad_manager
description: A new Flutter package project.
version: 0.7.0
homepage: https://twitter.com/hikeland
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.2
  freezed_annotation: ^2.4.1
  google_mobile_ads: ^3.0.0
  riverpod_annotation: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1 
  build_runner: ^2.4.6
  freezed: ^2.4.3
  riverpod_generator: ^2.3.2

flutter: