name: ad_manager
description: A new Flutter package project.
version: 0.5.0
homepage: https://twitter.com/hikeland
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  freezed_annotation: ^2.2.0
  google_mobile_ads: ^2.3.0
  riverpod_annotation: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1 
  build_runner: ^2.3.2
  freezed: ^2.2.1
  riverpod_generator: ^1.0.6

flutter: